services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skilllane_client
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - skilllane_network

networks:
  skilllane_network:
    driver: bridge
